### ISSUE TITLE
How can I pass strings using dynamic_invoke?

### ISSUE THREAD

**Issue by TheOnlyArtz** [Kudaes/DInvoke_rs#3] opened 2022-02-10 14:39 UTC
```rs
        let cmd: String = String::from("Echo dynamically loaded");

        let func_ptr:  unsafe extern "Rust" fn (*const c_char) -> *const c_char; // Function header
        let ret: Option<i32>; // The value that the called function will return
        unsafe {
            let parameter1 = cmd.as_ptr() as *const c_char;
            
            dinvoke::dynamic_invoke!(overload.1, "command", func_ptr, ret, parameter1);
        }
```
It throws
```
   |
86 |             dinvoke::dynamic_invoke!(overload.1, "command", func_ptr, ret, parameter1);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found *-ptr
   |
   = note:     expected type `i32`
           found raw pointer `*const i8
```

**Comment by Kudaes** [comment] 2022-02-10 15:57
Hi @TheOnlyArtz ,

I think the problem here is the return type. In the `func_ptr` variable, you are declaring the header of a function that returns a `*const c_char`. However, you are using an `Option<i32>` as return parameter. In my opinion, this should be fixed if you declare the variable `ret` as `Option<*const c_char>`. 

Let me know if this solves the issue.

**Comment by Kudaes** [comment] 2022-02-11 08:59
I'm pretty sure that the solution that I've provided you will fix the issue ;)

What I didn't know is that you were trying to run .NET code. As far as I know, Dinvoke_rs shouldn't be able to execute .NET code by itself since the CRL won't be available in the process, which probably explains why you are getting the ACCESS VIOLATION error message.

I'm closing the issue now since it looks like the expected behaviour. Do not hesitate to reach me via email or Twitter if you need any extra tips for using this project :)

**Closed by Kudaes** 2022-02-11 08:59 UTC
